In [16]:
import pandas as pd
from IPython.display import display

In [17]:
pop = pd.read_csv(r"C:\Users\MARE\Documents\data311_project2\data\raw\population_addresses_messy.csv")
pop.head()

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
0,POP_S_7315039,student,7917 J St,Eureka,CA,95501,6863 Cedar Ln,Redding,CA,96001,NorCal
1,POP_S_4194026,Student,1845 Bates Rd,McKinleyville,ca,95519,8942 Birch Pl,La Mesa,CA,91942,SanDiego
2,POP_S_4478952,Student,9921 Harris St,EUREKA,CA,95501,9527 Maple Dr,Redding,CA,96001,NorCal
3,POP_S_2541649,Student,3397 5th St,Eureka,CA,95501,1318 Meadow Blvd,National City,CA,91950,SanDiego
4,POP_S_4662231,Student,8466 H St,Eureka,CA,95501,3406 Meadow Pl,National City,CA,91950,SanDiego

In [18]:
summary = pd.DataFrame({
    "unique_values": pop.nunique(),
    "total_rows": len(pop),
    "all_values_unique": pop.apply(lambda col: col.is_unique),
    "missing_values": pop.isna().sum()
})

print(summary)

                  unique_values  total_rows  all_values_unique  missing_values
pop_id                     7629        7785              False               0
role                         13        7785              False               0
current_street             7449        7785              False              65
current_city                 25        7785              False              66
current_state                 6        7785              False               0
current_zip                  33        7785              False              86
permanent_street           7117        7785              False              56
permanent_city               76        7785              False               0
permanent_state              10        7785              False               0
permanent_zip                38        7785              False               0
permanent_region              6        7785              False               0

In [19]:
# Data Auddit
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 100)

In [20]:
#pop id
print("=" * 80)
print("1. DUPLICATE pop_id VALUES")
print("=" * 80)

duplicate_ids = pop[
    pop["pop_id"].notna()
    & pop["pop_id"].duplicated(keep=False)
].sort_values("pop_id")

if duplicate_ids.empty:
    print("No duplicate pop_id values found.")
else:
    print("Repeated IDs and their occurrence counts:")
    display(
        duplicate_ids["pop_id"]
        .value_counts()
        .rename_axis("pop_id")
        .reset_index(name="occurrences")
    )

    print("\nAll rows associated with repeated IDs:")
    display(duplicate_ids)

================================================================================
1. DUPLICATE pop_id VALUES
================================================================================
Repeated IDs and their occurrence counts:

             pop_id  occurrences
0     POP_S_1371371            3
1     POP_S_4940241            3
2     POP_F_1451911            2
3     POP_F_2001167            2
4     POP_F_2930051            2
5     POP_F_4417903            2
6     POP_F_7389365            2
7     POP_F_7849184            2
8     POP_F_8236540            2
9     POP_F_8683616            2
10    POP_F_9214923            2
11    POP_S_1089777            2
12    POP_S_1099258            2
13    POP_S_1103247            2
14    POP_S_1165846            2
15    POP_S_1287415            2
16    POP_S_1418046            2
17    POP_S_1494469            2
18    POP_S_1640872            2
19    POP_S_1657976            2
20    POP_S_1799330            2
21    POP_S_1842210            2
22    POP_S_1946021            2
23    POP_S_1946940            2
24    POP_S_2010506            2
25   POP_S_20708608            2
26    POP_S_2128308            2
27    POP_S_2146111            2
28    POP_S_2147567            2
29    POP_S_2156522            2
30    POP_S_2160998            2
31    POP_S_2226538            2
32    POP_S_2278326            2
33    POP_S_2391199            2
34    POP_S_2505498            2
35    POP_S_2537987            2
36   POP_S_26537991            2
37    POP_S_2724175            2
38    POP_S_2924400            2
39    POP_S_2978858            2
40    POP_S_2986324            2
41   POP_S_30568487            2
42    POP_S_3145357            2
43    POP_S_3206951            2
44    POP_S_3228520            2
45    POP_S_3379517            2
46    POP_S_3398448            2
47    POP_S_3426337            2
48    POP_S_3539399            2
49    POP_S_3609422            2
50    POP_S_3638484            2
51    POP_S_3665587            2
52    POP_S_3906489            2
53    POP_S_3972851            2
54   POP_S_39965747            2
55    POP_S_4002598            2
56    POP_S_4118143            2
57    POP_S_4123080            2
58    POP_S_4250915            2
59    POP_S_4328148            2
60    POP_S_4330855            2
61    POP_S_4423282            2
62   POP_S_44692542            2
63    POP_S_4508166            2
64    POP_S_4568979            2
65    POP_S_4597515            2
66    POP_S_4754922            2
67    POP_S_4755432            2
68    POP_S_4878269            2
69    POP_S_4937133            2
70    POP_S_4969034            2
71    POP_S_5003934            2
72    POP_S_5108019            2
73    POP_S_5138664            2
74    POP_S_5311728            2
75    POP_S_5360649            2
76    POP_S_5369563            2
77    POP_S_5396726            2
78    POP_S_5437455            2
79    POP_S_5586039            2
80    POP_S_5614862            2
81    POP_S_5622498            2
82    POP_S_5675853            2
83    POP_S_5694517            2
84    POP_S_5761686            2
85    POP_S_5764958            2
86    POP_S_5841930            2
87    POP_S_6027412            2
88    POP_S_6049622            2
89    POP_S_6074247            2
90    POP_S_6113051            2
91    POP_S_6159896            2
92    POP_S_6231223            2
93    POP_S_6235168            2
94    POP_S_6454735            2
95    POP_S_6577232            2
96    POP_S_6702559            2
97    POP_S_6718208            2
98   POP_S_70255285            2
99   POP_S_70346125            2
100   POP_S_7035177            2
101   POP_S_7040401            2
102   POP_S_7079262            2
103  POP_S_70952709            2
104   POP_S_7111489            2
105   POP_S_7166184            2
106   POP_S_7241667            2
107  POP_S_72947280            2
108   POP_S_7313129            2
109   POP_S_7322887            2
110   POP_S_7349222            2
111   POP_S_7355236            2
112   POP_S_7366358            2
113   POP_S_7433653            2
114   POP_S_7475445            2
115   POP_S_7548306            2
116   POP_S_7562508            2
117   POP_S_7563491            2
118   POP_S_7586801            2
119   POP_S_7607008            2
120   POP_S_7618346            2
121   POP_S_7631584            2
122   POP_S_7693823            2
123   POP_S_7809056            2
124   POP_S_7993182            2
125   POP_S_8086771            2
126  POP_S_80973785            2
127   POP_S_8207008            2
128   POP_S_8253947            2
129   POP_S_8396752            2
130   POP_S_8540441            2
131   POP_S_8743580            2
132   POP_S_8791857            2
133   POP_S_8936899            2
134   POP_S_8944744            2
135   POP_S_8966518            2
136   POP_S_9045855            2
137   POP_S_9088229            2
138   POP_S_9126301            2
139   POP_S_9354826            2
140   POP_S_9369120            2
141   POP_S_9408904            2
142   POP_S_9540063            2
143   POP_S_9551115            2
144   POP_S_9628639            2
145   POP_S_9650707            2
146   POP_S_9666230            2
147   POP_S_9695936            2
148   POP_S_9770391            2
149  POP_S_98257842            2
150   POP_S_9945653            2
151   POP_S_9948521            2
152   POP_S_9952831            2
153   POP_S_9973271            2

All rows associated with repeated IDs:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
7710,POP_F_1451911,Faculty,1100 G St,Arcata,CA,95521,1100 G St,ARCATA,CA,95521,Local
6160,POP_F_1451911,Faculty,1100 G St,Arcata,CA,95521,1100 G St,ARCATA,CA,95521,Local
7654,POP_F_2001167,Faculty,7238 Greenwood Ave,Blue Lake,CA,95525,7238 Greenwood Ave,Blue Lake,CA,95525,Local
6305,POP_F_2001167,Faculty,7238 Greenwood Ave,Blue Lake,CA,95525,7238 Greenwood Ave,Blue Lake,CA,95525,Local
7684,POP_F_2930051,Faculty,366 Q St,Arcata,CA,95521,366 Q St,Arcata,CA,95521,Local
...,...,...,...,...,...,...,...,...,...,...,...
3135,POP_S_9948521,Student,6124 Central Ave,McKinleyville,CA,95519,8447 Vista St,Phoenix,AZ,85004,OutOfState
1896,POP_S_9952831,Student,9825 Union St,Arcata,CA,95521,7419 Pine St,San Jose,CA,95112,BayArea
7664,POP_S_9952831,Student,9825 Union St,Arcata,CA,95521,7419 Pine St,San Jose,CA,95112,BayArea
7706,POP_S_9973271,Student,5488 h st,Arcata,CA,95521,5485 Canyon Dr,Chico,CA,95926,NorCal
4879,POP_S_9973271,Student,5488 h st,Arcata,CA,95521,5485 Canyon Dr,Chico,CA,95926,NorCal

In [21]:
#drop duplicate rows
pop_unique = pop.drop_duplicates()
#non-duplicate rows where pop_id is not unique (how do we handle?)
pop_unique[pop_unique.duplicated(subset = "pop_id", keep = False)].sort_values("pop_id")

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
1427,POP_S_1371371,Student,5576 G St,Arcata,CA,95521,282 Hill Ln,Glendale,CA,91203,LA
7163,POP_S_1371371,Staff/Admin,2570 Myrtle Ave,Eureka,CA,95501,2570 Myrtle Ave,EUREKA,CA,95501,Local
380,POP_S_4940241,Student,8640 Janis Ct,Arcata,OR,95521,7386 Lake Rd,Chico,CA,95926,NorCal
4552,POP_S_4940241,STUDENT,1466 Spears Rd,Arcata,CA,95521,6155 Spruce Dr,San Diego,CA,92103,SanDiego
3880,POP_S_6159896,Student,1695 G St,Arcata,CA,95521,2144 Willow Way,Austin,TX,78701,OutOfState
7097,POP_S_6159896,Staff/Admin,8317 WINCHESTER AVE,McKinleyville,CA,95519,5317 Winchester Ave,McKinleyville,CA,95519,Local
43,POP_S_7366358,Student,2208 Baldwin St,NaN,CA,95521,9805 Meadow Blvd,Fremont,CA,94536,BayArea
3554,POP_S_7366358,Student,2551 Union St,Arcata,CA,95521,421 Lake Rd,Santa Rosa,CA,95401,NorCal

In [22]:
#check that all remaining pop_id are of the correct format
pop_unique[pop_unique["pop_id"].astype(str).str.fullmatch(r"POP_[SFA]_\d+") == False]

Empty DataFrame
Columns: [pop_id, role, current_street, current_city, current_state, current_zip, permanent_street, permanent_city, permanent_state, permanent_zip, permanent_region]
Index: []

In [23]:
# Role audit
print("\n" + "=" * 80)
print("2. ROLE AUDIT")
print("=" * 80)

print("All role values and their frequencies:")
role_counts = (
    pop["role"]
    .value_counts(dropna=False)
    .rename_axis("role")
    .reset_index(name="count")
)
display(role_counts)

# Normalize capitalization and surrounding whitespace
role_normalized = pop["role"].astype("string").str.strip().str.casefold()

print("\nRoles after ignoring capitalization and outer whitespace:")
display(
    pop.assign(normalized_role=role_normalized)
       .groupby("normalized_role", dropna=False)
       .agg(
           count=("role", "size"),
           original_values=("role",
                            lambda x: sorted(x.dropna().unique().tolist()))
       )
       .reset_index()
)

================================================================================
2. ROLE AUDIT
================================================================================
All role values and their frequencies:

           role  count
0       Student   6164
1   Staff/Admin    683
2       Faculty    498
3       STUDENT    137
4       student    115
5       Studnet    112
6         Staff     15
7       faculty     11
8      Faculty      10
9       FACULTY     10
10  Staff-Admin     10
11  staff/admin     10
12  STAFF/ADMIN     10

Roles after ignoring capitalization and outer whitespace:

  normalized_role  count                          original_values
0         faculty    529    [FACULTY, Faculty, Faculty , faculty]
1           staff     15                                  [Staff]
2     staff-admin     10                            [Staff-Admin]
3     staff/admin    703  [STAFF/ADMIN, Staff/Admin, staff/admin]
4         student   6416              [STUDENT, Student, student]
5         studnet    112                                [Studnet]

In [24]:
#standardize role names and confirm 
pop_unique.loc[pop_unique["role"].str.startswith(("stu", "STU", "Stu")), "role"] = "student"
pop_unique.loc[pop_unique["role"].str.startswith(("sta", "STA", "Sta")), "role"] = "staff/admin"
pop_unique.loc[pop_unique["role"].str.startswith(("fac", "FAC", "Fac")), "role"] = "faculty"
pop = pop_unique
pop.query("role not in ['student', 'staff/admin', 'faculty']")

Empty DataFrame
Columns: [pop_id, role, current_street, current_city, current_state, current_zip, permanent_street, permanent_city, permanent_state, permanent_zip, permanent_region]
Index: []

In [25]:
print("All role values and their frequencies:")
role_counts = (
    pop["role"]
    .value_counts(dropna=False)
    .rename_axis("role")
    .reset_index(name="count")
)
display(role_counts)

All role values and their frequencies:

          role  count
0      student   6400
1  staff/admin    713
2      faculty    520

In [26]:
# Current Address Audit
current_columns = [
    "current_street",
    "current_city",
    "current_state",
    "current_zip"
]

print("\n" + "=" * 80)
print("3. CURRENT ADDRESS AUDIT")
print("=" * 80)

================================================================================
3. CURRENT ADDRESS AUDIT
================================================================================

In [27]:
# Current Address Audit
permanent_columns = [
    "permanent_street",
    "permanent_city",
    "permanent_state",
    "permanent_zip",
    "permanent_region"
]

print("\n" + "=" * 80)
print("4. PERMANENT ADDRESS AUDIT")
print("=" * 80)

================================================================================
4. PERMANENT ADDRESS AUDIT
================================================================================

In [28]:
def audit_duplicates(df, columns, address_type):
    for column in columns:
        print("\n" + "-" * 70)
        print(f"{address_type}: {column}")
        print("-" * 70)

        # Ignore missing values when identifying repeats
        counts = df[column].value_counts(dropna=True)
        repeated_values = counts[counts > 1]

        if repeated_values.empty:
            print("No repeated non-missing values found.")
            continue

        print("Repeated values and occurrence counts:")
        display(
            repeated_values
            .rename_axis(column)
            .reset_index(name="occurrences")
        )

        # Show every full row associated with a repeated value
        mask = (
            df[column].notna()
            & df[column].isin(repeated_values.index)
        )

        print("All rows containing those repeated values:")
        display(df.loc[mask].sort_values(column))


# Run the current address checks
audit_duplicates(pop, current_columns, "CURRENT ADDRESS")

# Run the permanent address checks
audit_duplicates(pop, permanent_columns, "PERMANENT ADDRESS")

----------------------------------------------------------------------
CURRENT ADDRESS: current_street
----------------------------------------------------------------------
Repeated values and occurrence counts:

         current_street  occurrences
0                     -           20
1               unknown           18
2             8571 Q St            3
3       7550 Samoa Blvd            2
4        173 Baldwin St            2
5             8223 K St            2
6     8332 LK Wood Blvd            2
7             3454 Q St            2
8       1457 Samoa Blvd            2
9       2395 Samoa Blvd            2
10          1021 5th St            2
11       3228 Hiller Rd            2
12     8747 Central Ave            2
13       3152 Murray Rd            2
14      7954 Baldwin St            2
15     7073 Alliance Rd            2
16       1087 Hiller Rd            2
17            9632 H St            2
18        1793 Bates Rd            2
19       299 Samoa Blvd            2
20      5575 Wabash Ave            2
21            5967 G St            2
22      1485 Samoa Blvd            2
23            4588 J St            2
24            8481 G St            2
25      8936 Baldwin St            2
26     6985 Alliance Rd            2
27      2808 Samoa Blvd            2
28            1421 H St            2
29         1009 Main St            2
30            5064 G St            2
31            6764 G St            2
32            8223 H St            2
33            5545 G St            2
34        6997 Union St            2
35            4063 H St            2
36     448 LK Wood Blvd            2
37            3456 K St            2
38        4033 Union St            2
39      4648 Samoa Blvd            2
40      1286 Baldwin St            2
41            7952 G St            2
42      5970 Myrtle Ave            2
43       2387 Hiller Rd            2
44     7989 Broadway St            2
45      4694 Myrtle Ave            2
46            6750 H St            2
47     9592 Central Ave            2
48    1741 LK Wood Blvd            2
49            1710 G St            2
50            8172 H St            2
51        2904 Janis Ct            2
52       9109 Spears Rd            2
53     7126 Alliance Rd            2
54      2256 Baldwin St            2
55        9516 Union St            2
56     2945 Hatchery Rd            2
57     9594 Central Ave            2
58       9989 Harris St            2
59            4419 J St            2
60      3010 Samoa Blvd            2
61          3998 5th St            2
62            7623 H St            2
63        8508 Union St            2
64      4342 Wabash Ave            2
65            5848 G St            2
66  7275 Winchester Ave            2
67   515 Winchester Ave            2
68            2556 J St            2
69            8973 G St            2
70        9629 Union St            2
71            3740 H St            2
72  8910 Winchester Ave            2
73        4088 Bates Rd            2
74    3681 LK Wood Blvd            2
75            7424 J St            2
76           655 5th St            2
77       8686 Murray Rd            2
78            4562 K St            2
79      3638 Baldwin St            2
80         7940 11th St            2
81            6628 Q St            2
82            1897 H St            2
83         1120 11th St            2
84            4087 Q St            2
85      8753 Wabash Ave            2

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
7494,POP_S_14842217,student,-,Arcata,CA,95521,6671 Elm Ave,Escondido,CA,92025,SanDiego
5616,POP_S_6680999,student,-,Arcata,CA,95521,3291 Spruce Pl,Seattle,WA,98101,OutOfState
1377,POP_S_4268441,student,-,Eureka,CA,95501,5725 Ridge Ave,Boulder,CO,80302,OutOfState
5393,POP_S_7770946,student,-,Arcata,CA,95521,3622 Canyon Ave,Ukiah,CA,95482,NorCal
1612,POP_S_4312891,student,-,Eureka,CA,95501,2316 Lake Blvd,San Francisco,CA,94110,BayArea
...,...,...,...,...,...,...,...,...,...,...,...
5139,POP_S_5937004,student,unknown,Eureka,CA,95501,685 Vista Blvd,Anaheim,CA,92801,LA
2374,POP_S_9046076,student,unknown,Arcata,CA,95521,5754 Pine Blvd,Seattle,WA,98101,OutOfState
4402,POP_S_2284475,student,unknown,Arcata,CA,95521,7381 Elm Rd,San Francisco,CA,94110,BayArea
536,POP_S_4571162,student,unknown,Eureka,CA,95501,2110 Maple Way,San Jose,CA,95112,BayArea
3277,POP_S_5518181,student,unknown,Arcata,CA,95521,1716 Elm Way,San Jose,CA,95112,BayArea

----------------------------------------------------------------------
CURRENT ADDRESS: current_city
----------------------------------------------------------------------
Repeated values and occurrence counts:

     current_city  occurrences
0          Arcata         3705
1          Eureka         1609
2   McKinleyville         1223
3       Blue Lake          215
4        Trinidad          172
5         Fortuna          166
6          arcata           66
7         ARCATRA           63
8          ARCATA           58
9         Arcatra           51
10         EUREKA           29
11        Eureaka           27
12         eureka           24
13         Eurika           24
14        unknown           21
15  MCKINLEYVILLE           21
16  mckinleyville           20
17  McKinelyville           20
18              -           19
19      BLUE LAKE            8
20        fortuna            6
21       BlueLake            6
22       Trinadad            5
23       TRINIDAD            5
24       Fortunna            4

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
2944,POP_S_8868267,student,2094 I St,-,CA,95501,1099 Cedar Ln,Sacramento,CA,95814,NorCal
4521,POP_S_6189807,student,9685 Harris St,-,CA,95501,2364 Hill St,San Diego,CA,92103,SanDiego
5290,POP_S_8808365,student,3540 Winchester Ave,-,CA,95519,7664 Ridge St,National City,CA,91950,SanDiego
1836,POP_S_2537987,student,7621 11th St,-,CA,95521,2821 Vista St,Daly City,CA,94015,BayArea
2394,POP_S_9164725,student,932 LK Wood Blvd,-,CA,95521,9044 Canyon Ln,Ukiah,CA,95482,NorCal
...,...,...,...,...,...,...,...,...,...,...,...
4563,POP_S_3041666,student,9098 Central Ave,unknown,CA,95519,575 Cedar St,Redding,CA,96001,NorCal
6625,POP_S_3587535,staff/admin,8981 H St,unknown,CA,95501,8981 H St,Eureka,CA,95501,Local
2263,POP_S_3823183,student,3610 G St,unknown,CA,95521,6744 Ridge St,La Mesa,CA,91942,SanDiego
980,POP_S_6214994,student,2204 Central Ave,unknown,CA,95519,8843 Willow Ave,Anaheim,CA,92801,LA
6812,POP_S_5286178,staff/admin,502 H St,unknown,CA,95521,502 H St,Arcata,CA,95521,Local

----------------------------------------------------------------------
CURRENT ADDRESS: current_state
----------------------------------------------------------------------
Repeated values and occurrence counts:

  current_state  occurrences
0            CA         7197
1            ca           96
2            Ca           94
3    California           83
4            OR           82
5           CA.           81

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
0,POP_S_7315039,student,7917 J St,Eureka,CA,95501,6863 Cedar Ln,Redding,CA,96001,NorCal
5021,POP_S_7131344,student,7461 LK Wood Blvd,Arcata,CA,95521,4046 Cedar Ave,Santa Monica,CA,90401,LA
5020,POP_S_4226255,student,1060 Union St,Arcata,CA,95521,1280 Maple Rd,Boise,ID,83702,OutOfState
5019,POP_S_1103247,student,5618 Bates Rd,McKinleyville,CA,9551,5785 Ridge Way,Seattle,WA,98101,OutOfState
5018,POP_S_6348319,student,4991 Winchester Ave,McKinleyville,CA,95519,6197 Maple Ln,Anaheim,CA,92801,LA
...,...,...,...,...,...,...,...,...,...,...,...
1232,POP_S_7771873,student,3665 Q St,Arcata,ca,95521,8452 Vista Dr,Berkeley,CA,94704,BayArea
2476,POP_S_4644270,student,6087 Q St,Arcata,ca,95521,485 Lake Dr,Fremont,CA,94536,BayArea
5465,POP_S_8699425,student,416 11th St,Arcata,ca,95521,8023 Maple Ave,Santa Rosa,CA,95401,NorCal
4569,POP_S_1446990,student,7695 Bates Rd,McKinleyville,ca,95519,1831 Ridge Pl,Los Angeles,CA,90026,LA
358,POP_S_7059938,student,1599 Janis Ct,Arcata,ca,95521,1061 Oak St,Fremont,CA,94536,BayArea

----------------------------------------------------------------------
CURRENT ADDRESS: current_zip
----------------------------------------------------------------------
Repeated values and occurrence counts:

   current_zip  occurrences
0        95521         3765
1        95501         1676
2        95519         1212
3        95525          219
4        95570          175
5        95540          165
6      95521.0           68
7         9552           59
8         9551           24
9      95519.0           21
10     unknown           19
11       59521           16
12     95501.0           15
13        9550           14
14           -           14
15       95512           14
16       95251           11
17       95051            8
18       59519            8
19       95591            7
20       95510            7
21     95525.0            4
22       59501            4
23        9554            4
24       95159            4
25     95540.0            4
26        9557            3
27       95450            2
28     95570.0            2

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
2826,POP_S_2705252,student,4309 Bates Rd,McKinleyville,CA,-,2109 Oak Dr,Brooklyn,NY,11211,OutOfState
6407,POP_F_1157200,faculty,2547 6th St,Eureka,CA,-,2547 6th St,Eureka,CA,95501,Local
933,POP_S_6974473,student,6359 H St,Arcata,CA,-,8866 Pine Rd,San Francisco,CA,94110,BayArea
1567,POP_S_4073010,student,6764 G St,Arcata,CA,-,6667 Birch Blvd,Berkeley,CA,94704,BayArea
5109,POP_S_1408429,student,3306 Q St,Arcata,CA,-,8181 Vista Blvd,Sacramento,CA,95814,NorCal
...,...,...,...,...,...,...,...,...,...,...,...
5347,POP_S_2747232,student,8347 LK Wood Blvd,Arcata,CA,unknown,4000 Ridge Rd,Oakland,CA,94612,BayArea
5775,POP_S_5246268,student,771 H St,Eureka,CA,unknown,2777 Elm Ave,National City,CA,91950,SanDiego
825,POP_S_7602003,student,5801 Winchester Ave,McKinleyville,CA,unknown,8213 Pine Rd,Sacramento,CA,95814,NorCal
3386,POP_S_5911561,student,7503 11th St,Arcata,CA,unknown,569 Spruce Pl,Pasadena,CA,91101,LA
4143,POP_S_4303405,student,1147 Heartwood Dr,McKinleyville,CA,unknown,6454 Maple Rd,Pasadena,CA,91101,LA

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_street
----------------------------------------------------------------------
Repeated values and occurrence counts:

    permanent_street  occurrences
0            unknown           33
1                  -           23
2     5095 Spruce Pl            3
3      6907 Ridge Rd            3
4       1756 Hill Ln            3
..               ...          ...
384   3988 Maple Way            2
385     2175 Lake Rd            2
386   8178 Spruce Ln            2
387        4087 Q St            2
388  8753 Wabash Ave            2

[389 rows x 2 columns]

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
5689,POP_S_3072591,student,9344 14th St,Arcata,CA,95521,-,San Jose,CA,95112,BayArea
7375,POP_S_87980251,student,2905 St Louis Rd #151,Arcata,CA,95521,-,Sacramento,CA,95814,NorCal
419,POP_S_7825990,student,9447 Baldwin St,Arcata,CA,95521,-,Oakland,CA,94612,BayArea
7291,POP_S_87410493,student,2905 St Louis Rd #219,Arcata,CA,95521,-,Brooklyn,NY,11211,OutOfState
360,POP_S_4066161,student,9371 Myrtle Ave,Eureka,CA,95501,-,Pasadena,CA,91101,LA
...,...,...,...,...,...,...,...,...,...,...,...
1039,POP_S_7498854,student,1277 11th St,Arcata,CA,95521,unknown,Phoenix,AZ,85004,OutOfState
4538,POP_S_3414900,student,2491 5th St,Eureka,CA,95501,unknown,San Jose,CA,95112,BayArea
6099,POP_F_8223650,faculty,192 Heartwood Dr,McKinleyville,CA,95519,unknown,McKinleyville,CA,95519,Local
6329,POP_F_2854831,faculty,1602 Winchester Ave,McKinleyville,CA,95519,unknown,McKinleyville,CA,95519,Local
5303,POP_S_4543192,student,182 Main St,Fortuna,CA,95540,unknown,Ukiah,CA,95482,NorCal

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_city
----------------------------------------------------------------------
Repeated values and occurrence counts:

    permanent_city  occurrences
0           Eureka          535
1    McKinleyville          316
2           Arcata          280
3         Glendale          266
4          Anaheim          260
5          Fremont          259
6         Pasadena          253
7      Los Angeles          251
8     Santa Monica          244
9        Daly City          236
10      Long Beach          235
11        Berkeley          231
12   San Francisco          230
13         Oakland          215
14        San Jose          205
15         Redding          191
16           Ukiah          185
17      Sacramento          180
18      Santa Rosa          179
19           Chico          167
20         Boulder          165
21  Salt Lake City          160
22        Portland          158
23         Seattle          153
24          Austin          152
25   National City          148
26        Brooklyn          145
27         Phoenix          138
28            Reno          138
29           Boise          136
30         La Mesa          130
31       Oceanside          123
32       Escondido          121
33     Chula Vista          116
34       San Diego          114
35       Blue Lake           64
36         Fortuna           64
37        Trinidad           54
38          EUREKA           32
39    SANTA MONICA           22
40       DALY CITY           22
41   MCKINLEYVILLE           18
42          ARCATA           18
43         FREMONT           17
44        GLENDALE           16
45        BERKELEY           16
46      LONG BEACH           16
47     LOS ANGELES           16
48         OAKLAND           16
49           UKIAH           15
50        PASADENA           14
51           CHICO           13
52          AUSTIN           12
53        PORTLAND           12
54      SACRAMENTO           12
55      SANTA ROSA           11
56         REDDING           10
57            RENO           10
58   SAN FRANCISCO           10
59  SALT LAKE CITY            9
60         ANAHEIM            9
61        BROOKLYN            9
62         BOULDER            8
63         FORTUNA            8
64         PHOENIX            7
65     CHULA VISTA            7
66           BOISE            7
67        SAN JOSE            7
68       OCEANSIDE            6
69         SEATTLE            6
70         LA MESA            6
71   NATIONAL CITY            6
72       ESCONDIDO            5
73       BLUE LAKE            4
74       SAN DIEGO            3

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
1793,POP_S_5758822,student,5986 Janis Ct,Arcata,CA,95521,1174 Pine Way,ANAHEIM,CA,92801,LA
1682,POP_S_3070685,student,8031 11th St,Arcata,CA,95521,7637 Canyon Rd,ANAHEIM,CA,92801,LA
4626,POP_S_1297384,student,209 Baldwin St,Arcata,CA,95521,5643 Cedar Ave,ANAHEIM,CA,92801,LA
917,POP_S_3678042,student,7164 Baldwin St,Arcata,CA,95521,1238 Elm Way,ANAHEIM,CA,92801,LA
5446,POP_S_7548306,student,9846 K St,Eureka,CA,95501,3823 Willow Pl,ANAHEIM,CA,92801,LA
...,...,...,...,...,...,...,...,...,...,...,...
5858,POP_S_7525082,student,2257 Samoa Blvd,Arcata,CA.,95521,7981 Ridge Dr,Ukiah,CA,95482,NorCal
3054,POP_S_3898140,student,7850 Samoa Blvd,Arcata,CA,95521,862 Birch St,Ukiah,CA,95482,NorCal
407,POP_S_5062717,student,6265 H St,Eureka,CA,95501,9196 Hill Pl,Ukiah,CA,95482,NorCal
1218,POP_S_2301910,student,9001 Samoa Blvd,Arcatra,CA,95521,4097 Spruce Ave,Ukiah,CA,95482,NorCal
1954,POP_S_8309635,student,5149 Union St,Arcata,CA,95521,9080 Hill Blvd,Ukiah,CA,95482,NorCal

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_state
----------------------------------------------------------------------
Repeated values and occurrence counts:

  permanent_state  occurrences
0              CA         6208
1              CO          173
2              OR          170
3              UT          169
4              TX          164
5              WA          159
6              NY          154
7              NV          148
8              AZ          145
9              ID          143

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
4628,POP_S_8207488,student,7871 H St,Arcata,CA,95521,9422 Canyon Pl,Phoenix,AZ,85004,OutOfState
3044,POP_S_6765655,student,3218 Union St,Arcata,CA,95521,2641 Oak St,Phoenix,AZ,85004,OutOfState
3000,POP_S_7215829,student,5881 Heartwood Dr,McKinleyville,CA,95519,3111 Willow Ave,Phoenix,AZ,85004,OutOfState
2999,POP_S_2510075,student,6328 Baldwin St,Arcata,CA,59521,2184 Elm Ln,Phoenix,AZ,85004,OutOfState
4265,POP_S_9226405,student,989 Winchester Ave,McKinleyville,CA,95519,2382 Oak St,Phoenix,AZ,85004,OutOfState
...,...,...,...,...,...,...,...,...,...,...,...
2938,POP_S_7480297,student,9566 Spears Rd,Arcata,CA,95521,4155 Oak Ln,Seattle,WA,98101,OutOfState
5884,POP_S_9263282,student,6049 Spears Rd,Arcata,CA,95521,9570 Willow Dr,Seattle,WA,98101,OutOfState
1656,POP_S_8505315,student,1099 Edwards St,Trinidad,CA,95570,2765 Oak St,Seattle,WA,98101,OutOfState
5811,POP_S_7465173,student,7816 J St,Eureka,CA,95501,6978 Elm Way,Seattle,WA,98101,OutOfState
872,POP_S_7248111,student,610 14th St,Arcata,CA,95521,NaN,Seattle,WA,98101,OutOfState

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_zip
----------------------------------------------------------------------
Repeated values and occurrence counts:

    permanent_zip  occurrences
0           95501          567
1           95519          334
2           95521          298
3           91203          282
4           94536          276
5           92801          269
6           91101          267
7           90026          267
8           90401          266
9           94015          258
10          90802          251
11          94704          247
12          94110          240
13          94612          231
14          95112          212
15          96001          201
16          95482          200
17          95814          192
18          95401          190
19          95926          180
20          80302          173
21          97205          170
22          84111          169
23          78701          164
24          98101          159
25          91950          154
26          11211          154
27          89501          148
28          85004          145
29          83702          143
30          91942          136
31          92054          129
32          92025          126
33          91910          123
34          92103          117
35          95540           72
36          95525           68
37          95570           55

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
3225,POP_S_7693823,student,5449 5th st,Eureka,CA,95501,1642 Sunset Way,Brooklyn,NY,11211,OutOfState
7624,POP_S_34207562,student,2905 St. Louis Road Apt 517,Arcata,CA,95521,324 Vista Way,Brooklyn,NY,11211,OutOfState
7600,POP_S_26053585,student,2905 St Louis Rd #651,Arcata,CA,95521,8248 Hill Rd,Brooklyn,NY,11211,OutOfState
372,POP_S_5044154,student,2047 Alliance Rd,Arcata,CA,95521,820 Willow Dr,Brooklyn,NY,11211,OutOfState
368,POP_S_2065588,student,4981 H St,Eureka,CA,95501,9802 Cedar Rd,Brooklyn,NY,11211,OutOfState
...,...,...,...,...,...,...,...,...,...,...,...
7282,POP_S_83625519,student,2905 St Louis Rd #153,Arcata,CA,95521,9037 Ridge Blvd,Seattle,WA,98101,OutOfState
108,POP_S_9106735,student,2460 Q St,Arcata,CA,95521,6699 Canyon Blvd,Seattle,WA,98101,OutOfState
65,POP_S_1792822,student,7940 School Rd,McKinleyville,CA,95519,1568 Oak Ln,Seattle,WA,98101,OutOfState
4568,POP_S_3756184,student,5690 Alliance Rd,Arcata,CA,95521,3188 Ridge Blvd,Seattle,WA,98101,OutOfState
4560,POP_S_4202922,student,4931 Winchester Ave,NaN,CA,95519,4721 Oak Ln,Seattle,WA,98101,OutOfState

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_region
----------------------------------------------------------------------
Repeated values and occurrence counts:

  permanent_region  occurrences
0               LA         1602
1          BayArea         1464
2       OutOfState         1425
3            Local         1233
4           NorCal         1124
5         SanDiego          785

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
2798,POP_S_9591254,student,666 Wabash Ave,Eureka,CA,95501,-,Daly City,CA,94015,BayArea
3873,POP_S_1855771,student,1412 I St,Eureka,CA,95501,8792 Ridge Ave,Daly City,CA,94015,BayArea
1413,POP_S_7452240,student,5253 6th St,Eureka,CA,95501,8250 Sunset Blvd,Fremont,CA,94536,BayArea
3888,POP_S_3205610,student,2979 patrick point dr,Trinidad,CA,95570,3089 Maple St,Berkeley,CA,94704,BayArea
3890,POP_S_5029427,student,3626 Janis Ct,Arcata,CA,95521,1600 Ridge Pl,Fremont,CA,94536,BayArea
...,...,...,...,...,...,...,...,...,...,...,...
1996,POP_S_2606285,student,2985 Janis Ct,Arcata,CA,95521,8695 Maple Blvd,Chula Vista,CA,91910,SanDiego
4504,POP_S_9619821,student,4306 Union St,Arcata,CA,95521,1552 Meadow Rd,La Mesa,CA,91942,SanDiego
1987,POP_S_7056598,student,6305 K St,Eureka,CA,95501,NaN,Oceanside,CA,92054,SanDiego
4480,POP_S_1900638,student,1474 14th St,Arcata,CA,95521,4048 Elm Rd,La Mesa,CA,91942,SanDiego
7632,POP_S_83300068,student,2905 St Louis Rd #618,Arcata,CA,95521,2674 Hill Way,San Diego,CA,92103,SanDiego

In [29]:
# Find Case and Whitespace
def audit_format_variations(df, columns, address_type):
    for column in columns:
        # Convert to strings, trim outer spaces, ignore case
        normalized = (
            df[column]
            .astype("string")
            .str.strip()
            .str.casefold()
        )

        # Preserve original spellings for comparison
        temp = pd.DataFrame({
            "normalized_value": normalized,
            "original_value": df[column]
        }).dropna(subset=["normalized_value"])

        variations = (
            temp.groupby("normalized_value")["original_value"]
            .agg(lambda x: sorted(x.unique().tolist()))
        )

        # Keep only groups with multiple original representations
        variations = variations[variations.map(len) > 1]

        if not variations.empty:
            print(
                f"\n{address_type} FORMAT VARIATIONS: {column}"
            )
            display(variations.rename("original_variations").reset_index())


print("\n" + "=" * 80)
print("5. CASE AND WHITESPACE VARIATIONS")
print("=" * 80)

audit_format_variations(
    pop,
    ["role"] + current_columns + permanent_columns,
    "ROLE / ADDRESS"
)

print("\n" + "=" * 80)
print("DATA-QUALITY AUDIT COMPLETE")
print("=" * 80)

================================================================================
5. CASE AND WHITESPACE VARIATIONS
================================================================================

ROLE / ADDRESS FORMAT VARIATIONS: current_street

   normalized_value                   original_variations
0     3200 janis ct        [3200 Janis Ct, 3200 janis ct]
1          322 h st                  [322 H St, 322 h st]
2    3334 murray rd      [3334 MURRAY RD, 3334 Murray Rd]
3  4742 alliance rd  [4742 ALLIANCE RD, 4742 Alliance Rd]
4  5073 central ave  [5073 Central Ave, 5073 central ave]
5      6141 11th st          [6141 11th St, 6141 11th st]
6   6325 myrtle ave    [6325 Myrtle Ave, 6325 myrtle ave]
7          636 g st                  [636 G St, 636 g st]
8   6453 wabash ave    [6453 Wabash Ave, 6453 wabash ave]
9          659 h st                  [659 H St, 659 h st]

ROLE / ADDRESS FORMAT VARIATIONS: current_city

  normalized_value                            original_variations
0           arcata                       [ARCATA, Arcata, arcata]
1          arcatra                             [ARCATRA, Arcatra]
2        blue lake                         [BLUE LAKE, Blue Lake]
3           eureka                       [EUREKA, Eureka, eureka]
4          fortuna                             [Fortuna, fortuna]
5    mckinleyville  [MCKINLEYVILLE, McKinleyville, mckinleyville]
6         trinidad                           [TRINIDAD, Trinidad]

ROLE / ADDRESS FORMAT VARIATIONS: current_state

  normalized_value original_variations
0               ca        [CA, Ca, ca]

ROLE / ADDRESS FORMAT VARIATIONS: permanent_city

   normalized_value               original_variations
0           anaheim                [ANAHEIM, Anaheim]
1            arcata                  [ARCATA, Arcata]
2            austin                  [AUSTIN, Austin]
3          berkeley              [BERKELEY, Berkeley]
4         blue lake            [BLUE LAKE, Blue Lake]
5             boise                    [BOISE, Boise]
6           boulder                [BOULDER, Boulder]
7          brooklyn              [BROOKLYN, Brooklyn]
8             chico                    [CHICO, Chico]
9       chula vista        [CHULA VISTA, Chula Vista]
10        daly city            [DALY CITY, Daly City]
11        escondido            [ESCONDIDO, Escondido]
12           eureka                  [EUREKA, Eureka]
13          fortuna                [FORTUNA, Fortuna]
14          fremont                [FREMONT, Fremont]
15         glendale              [GLENDALE, Glendale]
16          la mesa                [LA MESA, La Mesa]
17       long beach          [LONG BEACH, Long Beach]
18      los angeles        [LOS ANGELES, Los Angeles]
19    mckinleyville    [MCKINLEYVILLE, McKinleyville]
20    national city    [NATIONAL CITY, National City]
21          oakland                [OAKLAND, Oakland]
22        oceanside            [OCEANSIDE, Oceanside]
23         pasadena              [PASADENA, Pasadena]
24          phoenix                [PHOENIX, Phoenix]
25         portland              [PORTLAND, Portland]
26          redding                [REDDING, Redding]
27             reno                      [RENO, Reno]
28       sacramento          [SACRAMENTO, Sacramento]
29   salt lake city  [SALT LAKE CITY, Salt Lake City]
30        san diego            [SAN DIEGO, San Diego]
31    san francisco    [SAN FRANCISCO, San Francisco]
32         san jose              [SAN JOSE, San Jose]
33     santa monica      [SANTA MONICA, Santa Monica]
34       santa rosa          [SANTA ROSA, Santa Rosa]
35          seattle                [SEATTLE, Seattle]
36         trinidad              [TRINIDAD, Trinidad]
37            ukiah                    [UKIAH, Ukiah]

================================================================================
DATA-QUALITY AUDIT COMPLETE
================================================================================