In [5]:
import pandas as pd
from IPython.display import display

In [6]:
pop = pd.read_csv(r"C:\Users\MARE\Documents\data311_project2\data\raw\population_addresses_messy.csv")
pop.head()

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
0,POP_S_7315039,student,7917 J St,Eureka,CA,95501,6863 Cedar Ln,Redding,CA,96001,NorCal
1,POP_S_4194026,Student,1845 Bates Rd,McKinleyville,ca,95519,8942 Birch Pl,La Mesa,CA,91942,SanDiego
2,POP_S_4478952,Student,9921 Harris St,EUREKA,CA,95501,9527 Maple Dr,Redding,CA,96001,NorCal
3,POP_S_2541649,Student,3397 5th St,Eureka,CA,95501,1318 Meadow Blvd,National City,CA,91950,SanDiego
4,POP_S_4662231,Student,8466 H St,Eureka,CA,95501,3406 Meadow Pl,National City,CA,91950,SanDiego

In [7]:
summary = pd.DataFrame({
    "unique_values": pop.nunique(),
    "total_rows": len(pop),
    "all_values_unique": pop.apply(lambda col: col.is_unique),
    "missing_values": pop.isna().sum()
})

print(summary)

                  unique_values  total_rows  all_values_unique  missing_values
pop_id                     7629        7785              False               0
role                         13        7785              False               0
current_street             7449        7785              False              65
current_city                 25        7785              False              66
current_state                 6        7785              False               0
current_zip                  33        7785              False              86
permanent_street           7117        7785              False              56
permanent_city               76        7785              False               0
permanent_state              10        7785              False               0
permanent_zip                38        7785              False               0
permanent_region              6        7785              False               0

In [8]:
# Data Auddit
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 100)

In [9]:
#pop id
print("=" * 80)
print("1. DUPLICATE pop_id VALUES")
print("=" * 80)

duplicate_ids = pop[
    pop["pop_id"].notna()
    & pop["pop_id"].duplicated(keep=False)
].sort_values("pop_id")

if duplicate_ids.empty:
    print("No duplicate pop_id values found.")
else:
    print("Repeated IDs and their occurrence counts:")
    display(
        duplicate_ids["pop_id"]
        .value_counts()
        .rename_axis("pop_id")
        .reset_index(name="occurrences")
    )

    print("\nAll rows associated with repeated IDs:")
    display(duplicate_ids)

================================================================================
1. DUPLICATE pop_id VALUES
================================================================================
Repeated IDs and their occurrence counts:

             pop_id  occurrences
0     POP_S_1371371            3
1     POP_S_4940241            3
2     POP_F_1451911            2
3     POP_F_2001167            2
4     POP_F_2930051            2
5     POP_F_4417903            2
6     POP_F_7389365            2
7     POP_F_7849184            2
8     POP_F_8236540            2
9     POP_F_8683616            2
10    POP_F_9214923            2
11    POP_S_1089777            2
12    POP_S_1099258            2
13    POP_S_1103247            2
14    POP_S_1165846            2
15    POP_S_1287415            2
16    POP_S_1418046            2
17    POP_S_1494469            2
18    POP_S_1640872            2
19    POP_S_1657976            2
20    POP_S_1799330            2
21    POP_S_1842210            2
22    POP_S_1946021            2
23    POP_S_1946940            2
24    POP_S_2010506            2
25   POP_S_20708608            2
26    POP_S_2128308            2
27    POP_S_2146111            2
28    POP_S_2147567            2
29    POP_S_2156522            2
30    POP_S_2160998            2
31    POP_S_2226538            2
32    POP_S_2278326            2
33    POP_S_2391199            2
34    POP_S_2505498            2
35    POP_S_2537987            2
36   POP_S_26537991            2
37    POP_S_2724175            2
38    POP_S_2924400            2
39    POP_S_2978858            2
40    POP_S_2986324            2
41   POP_S_30568487            2
42    POP_S_3145357            2
43    POP_S_3206951            2
44    POP_S_3228520            2
45    POP_S_3379517            2
46    POP_S_3398448            2
47    POP_S_3426337            2
48    POP_S_3539399            2
49    POP_S_3609422            2
50    POP_S_3638484            2
51    POP_S_3665587            2
52    POP_S_3906489            2
53    POP_S_3972851            2
54   POP_S_39965747            2
55    POP_S_4002598            2
56    POP_S_4118143            2
57    POP_S_4123080            2
58    POP_S_4250915            2
59    POP_S_4328148            2
60    POP_S_4330855            2
61    POP_S_4423282            2
62   POP_S_44692542            2
63    POP_S_4508166            2
64    POP_S_4568979            2
65    POP_S_4597515            2
66    POP_S_4754922            2
67    POP_S_4755432            2
68    POP_S_4878269            2
69    POP_S_4937133            2
70    POP_S_4969034            2
71    POP_S_5003934            2
72    POP_S_5108019            2
73    POP_S_5138664            2
74    POP_S_5311728            2
75    POP_S_5360649            2
76    POP_S_5369563            2
77    POP_S_5396726            2
78    POP_S_5437455            2
79    POP_S_5586039            2
80    POP_S_5614862            2
81    POP_S_5622498            2
82    POP_S_5675853            2
83    POP_S_5694517            2
84    POP_S_5761686            2
85    POP_S_5764958            2
86    POP_S_5841930            2
87    POP_S_6027412            2
88    POP_S_6049622            2
89    POP_S_6074247            2
90    POP_S_6113051            2
91    POP_S_6159896            2
92    POP_S_6231223            2
93    POP_S_6235168            2
94    POP_S_6454735            2
95    POP_S_6577232            2
96    POP_S_6702559            2
97    POP_S_6718208            2
98   POP_S_70255285            2
99   POP_S_70346125            2
100   POP_S_7035177            2
101   POP_S_7040401            2
102   POP_S_7079262            2
103  POP_S_70952709            2
104   POP_S_7111489            2
105   POP_S_7166184            2
106   POP_S_7241667            2
107  POP_S_72947280            2
108   POP_S_7313129            2
109   POP_S_7322887            2
110   POP_S_7349222            2
111   POP_S_7355236            2
112   POP_S_7366358            2
113   POP_S_7433653            2
114   POP_S_7475445            2
115   POP_S_7548306            2
116   POP_S_7562508            2
117   POP_S_7563491            2
118   POP_S_7586801            2
119   POP_S_7607008            2
120   POP_S_7618346            2
121   POP_S_7631584            2
122   POP_S_7693823            2
123   POP_S_7809056            2
124   POP_S_7993182            2
125   POP_S_8086771            2
126  POP_S_80973785            2
127   POP_S_8207008            2
128   POP_S_8253947            2
129   POP_S_8396752            2
130   POP_S_8540441            2
131   POP_S_8743580            2
132   POP_S_8791857            2
133   POP_S_8936899            2
134   POP_S_8944744            2
135   POP_S_8966518            2
136   POP_S_9045855            2
137   POP_S_9088229            2
138   POP_S_9126301            2
139   POP_S_9354826            2
140   POP_S_9369120            2
141   POP_S_9408904            2
142   POP_S_9540063            2
143   POP_S_9551115            2
144   POP_S_9628639            2
145   POP_S_9650707            2
146   POP_S_9666230            2
147   POP_S_9695936            2
148   POP_S_9770391            2
149  POP_S_98257842            2
150   POP_S_9945653            2
151   POP_S_9948521            2
152   POP_S_9952831            2
153   POP_S_9973271            2

All rows associated with repeated IDs:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
7710,POP_F_1451911,Faculty,1100 G St,Arcata,CA,95521,1100 G St,ARCATA,CA,95521,Local
6160,POP_F_1451911,Faculty,1100 G St,Arcata,CA,95521,1100 G St,ARCATA,CA,95521,Local
7654,POP_F_2001167,Faculty,7238 Greenwood Ave,Blue Lake,CA,95525,7238 Greenwood Ave,Blue Lake,CA,95525,Local
6305,POP_F_2001167,Faculty,7238 Greenwood Ave,Blue Lake,CA,95525,7238 Greenwood Ave,Blue Lake,CA,95525,Local
7684,POP_F_2930051,Faculty,366 Q St,Arcata,CA,95521,366 Q St,Arcata,CA,95521,Local
...,...,...,...,...,...,...,...,...,...,...,...
3135,POP_S_9948521,Student,6124 Central Ave,McKinleyville,CA,95519,8447 Vista St,Phoenix,AZ,85004,OutOfState
1896,POP_S_9952831,Student,9825 Union St,Arcata,CA,95521,7419 Pine St,San Jose,CA,95112,BayArea
7664,POP_S_9952831,Student,9825 Union St,Arcata,CA,95521,7419 Pine St,San Jose,CA,95112,BayArea
7706,POP_S_9973271,Student,5488 h st,Arcata,CA,95521,5485 Canyon Dr,Chico,CA,95926,NorCal
4879,POP_S_9973271,Student,5488 h st,Arcata,CA,95521,5485 Canyon Dr,Chico,CA,95926,NorCal

In [10]:
# Role audit
print("\n" + "=" * 80)
print("2. ROLE AUDIT")
print("=" * 80)

print("All role values and their frequencies:")
role_counts = (
    pop["role"]
    .value_counts(dropna=False)
    .rename_axis("role")
    .reset_index(name="count")
)
display(role_counts)

# Normalize capitalization and surrounding whitespace
role_normalized = pop["role"].astype("string").str.strip().str.casefold()

print("\nRoles after ignoring capitalization and outer whitespace:")
display(
    pop.assign(normalized_role=role_normalized)
       .groupby("normalized_role", dropna=False)
       .agg(
           count=("role", "size"),
           original_values=("role",
                            lambda x: sorted(x.dropna().unique().tolist()))
       )
       .reset_index()
)

================================================================================
2. ROLE AUDIT
================================================================================
All role values and their frequencies:

           role  count
0       Student   6164
1   Staff/Admin    683
2       Faculty    498
3       STUDENT    137
4       student    115
5       Studnet    112
6         Staff     15
7       faculty     11
8      Faculty      10
9       FACULTY     10
10  Staff-Admin     10
11  staff/admin     10
12  STAFF/ADMIN     10

Roles after ignoring capitalization and outer whitespace:

  normalized_role  count                          original_values
0         faculty    529    [FACULTY, Faculty, Faculty , faculty]
1           staff     15                                  [Staff]
2     staff-admin     10                            [Staff-Admin]
3     staff/admin    703  [STAFF/ADMIN, Staff/Admin, staff/admin]
4         student   6416              [STUDENT, Student, student]
5         studnet    112                                [Studnet]

In [11]:
# Current Address Audit
current_columns = [
    "current_street",
    "current_city",
    "current_state",
    "current_zip"
]

print("\n" + "=" * 80)
print("3. CURRENT ADDRESS AUDIT")
print("=" * 80)

================================================================================
3. CURRENT ADDRESS AUDIT
================================================================================

In [12]:
# Current Address Audit
permanent_columns = [
    "permanent_street",
    "permanent_city",
    "permanent_state",
    "permanent_zip",
    "permanent_region"
]

print("\n" + "=" * 80)
print("4. PERMANENT ADDRESS AUDIT")
print("=" * 80)

================================================================================
4. PERMANENT ADDRESS AUDIT
================================================================================

In [13]:
def audit_duplicates(df, columns, address_type):
    for column in columns:
        print("\n" + "-" * 70)
        print(f"{address_type}: {column}")
        print("-" * 70)

        # Ignore missing values when identifying repeats
        counts = df[column].value_counts(dropna=True)
        repeated_values = counts[counts > 1]

        if repeated_values.empty:
            print("No repeated non-missing values found.")
            continue

        print("Repeated values and occurrence counts:")
        display(
            repeated_values
            .rename_axis(column)
            .reset_index(name="occurrences")
        )

        # Show every full row associated with a repeated value
        mask = (
            df[column].notna()
            & df[column].isin(repeated_values.index)
        )

        print("All rows containing those repeated values:")
        display(df.loc[mask].sort_values(column))


# Run the current address checks
audit_duplicates(pop, current_columns, "CURRENT ADDRESS")

# Run the permanent address checks
audit_duplicates(pop, permanent_columns, "PERMANENT ADDRESS")

----------------------------------------------------------------------
CURRENT ADDRESS: current_street
----------------------------------------------------------------------
Repeated values and occurrence counts:

            current_street  occurrences
0                        -           20
1                  unknown           18
2                8571 Q St            3
3           1087 Hiller Rd            3
4          2808 Samoa Blvd            3
..                     ...          ...
228  2905 St Louis Rd #306            2
229  2905 St Louis Rd #417            2
230  2905 St Louis Rd #132            2
231  2905 St Louis Rd #513            2
232  2905 St Louis Rd #708            2

[233 rows x 2 columns]

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
1377,POP_S_4268441,Student,-,Eureka,CA,95501,5725 Ridge Ave,Boulder,CO,80302,OutOfState
7494,POP_S_14842217,Student,-,Arcata,CA,95521,6671 Elm Ave,Escondido,CA,92025,SanDiego
764,POP_S_5029972,Student,-,Arcata,CA,95521,2446 Meadow Rd,Santa Monica,CA,90401,LA
4888,POP_S_2701322,Student,-,Arcata,CA,95521,7333 Spruce Ave,San Jose,CA,95112,BayArea
1695,POP_S_6549858,Student,-,Blue Lake,CA,95525,7197 Cedar Dr,La Mesa,CA,91942,SanDiego
...,...,...,...,...,...,...,...,...,...,...,...
3939,POP_S_6697615,Student,unknown,Arcata,CA,95521,4150 Maple Blvd,Fremont,CA,94536,BayArea
5139,POP_S_5937004,Student,unknown,Eureka,CA,95501,685 Vista Blvd,Anaheim,CA,92801,LA
2374,POP_S_9046076,Student,unknown,Arcata,CA,95521,5754 Pine Blvd,Seattle,WA,98101,OutOfState
3758,POP_S_5860192,Student,unknown,Eureka,CA,95501,4357 Willow Ln,Eureka,CA,95501,NorCal
4402,POP_S_2284475,Student,unknown,Arcata,CA,95521,7381 Elm Rd,San Francisco,CA,94110,BayArea

----------------------------------------------------------------------
CURRENT ADDRESS: current_city
----------------------------------------------------------------------
Repeated values and occurrence counts:

     current_city  occurrences
0          Arcata         3777
1          Eureka         1644
2   McKinleyville         1249
3       Blue Lake          218
4        Trinidad          174
5         Fortuna          169
6          arcata           67
7         ARCATRA           64
8          ARCATA           59
9         Arcatra           51
10         EUREKA           30
11        Eureaka           28
12         eureka           26
13         Eurika           25
14        unknown           22
15  mckinleyville           21
16  MCKINLEYVILLE           21
17              -           20
18  McKinelyville           20
19      BLUE LAKE            8
20        fortuna            6
21       BlueLake            6
22       Trinadad            5
23       TRINIDAD            5
24       Fortunna            4

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
2624,POP_S_3259236,Student,2105 11th St,-,CA,95521,5210 Sunset Way,Fremont,CA,94536,BayArea
7217,POP_S_3623368,Staff/Admin,8561 Main St,-,CA,95570,8561 Main St,Trinidad,CA,95570,Local
7713,POP_S_2537987,Student,7621 11th St,-,CA,95521,2821 Vista St,Daly City,CA,94015,BayArea
5571,POP_S_7791606,Student,5027 Winchester Ave,-,CA,95519,782 Spruce Way,Phoenix,AZ,85004,OutOfState
225,POP_S_2826107,Student,6611 Murray Rd,-,CA,95519,8367 Canyon Rd,Boise,ID,83702,OutOfState
...,...,...,...,...,...,...,...,...,...,...,...
5891,POP_S_6113051,Student,4232 Union St,unknown,CA,95521,2682 Spruce St,Salt Lake City,UT,84111,OutOfState
760,POP_S_7063727,Student,3162 11th St,unknown,CA,95521,3274 Vista Blvd,National City,CA,91950,SanDiego
6812,POP_S_5286178,Staff/Admin,502 H St,unknown,CA,95521,502 H St,Arcata,CA,95521,Local
6828,POP_S_6142120,Staff/Admin,5274 Winchester Ave,unknown,CA,95519,5274 Winchester Ave,McKinleyville,CA,95519,Local
980,POP_S_6214994,Student,2204 Central Ave,unknown,CA,95519,8843 Willow Ave,Anaheim,CA,92801,LA

----------------------------------------------------------------------
CURRENT ADDRESS: current_state
----------------------------------------------------------------------
Repeated values and occurrence counts:

  current_state  occurrences
0            CA         7336
1            ca           98
2            Ca           97
3            OR           86
4    California           85
5           CA.           83

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
0,POP_S_7315039,student,7917 J St,Eureka,CA,95501,6863 Cedar Ln,Redding,CA,96001,NorCal
5124,POP_S_6166886,Student,9881 rohnerville rd,Fortuna,CA,95540,813 Lake Way,Sacramento,CA,95814,NorCal
5123,POP_S_1098353,Student,-,Eureka,CA,95501,9092 Oak Rd,Chula Vista,CA,91910,SanDiego
5122,POP_S_1661349,Student,6545 11th St,Arcata,CA,95521,4175 Sunset Ave,Seattle,WA,98101,OutOfState
5121,POP_S_6549634,Student,5223 Baldwin St,Arcata,CA,95521,3838 Spruce Rd,Salt Lake City,UT,84111,OutOfState
...,...,...,...,...,...,...,...,...,...,...,...
7124,POP_S_6532262,Staff/Admin,2739 I St,Eureka,ca,95501,2739 I St,Eureka,CA,95501,Local
6256,POP_F_8637197,Faculty,5885 Wabash Ave,Eureka,ca,95501,5885 Wabash Ave,Eureka,CA,95501,Local
1096,POP_S_2406249,Student,3655 H St,Eureka,ca,95501,403 Hill St,Berkeley,CA,94704,BayArea
4287,POP_S_2165888,Student,8243 H St,Eureka,ca,95501,6877 Cedar Rd,Los Angeles,CA,90026,LA
7784,POP_S_5614862,Student,4299 5th St,Eureka,ca,95501,4084 Maple Way,Daly City,CA,94015,BayArea

----------------------------------------------------------------------
CURRENT ADDRESS: current_zip
----------------------------------------------------------------------
Repeated values and occurrence counts:

   current_zip  occurrences
0        95521         3840
1        95501         1715
2        95519         1235
3        95525          222
4        95570          177
5        95540          168
6      95521.0           69
7         9552           59
8         9551           27
9      95519.0           21
10     unknown           19
11       59521           17
12     95501.0           15
13        9550           14
14           -           14
15       95512           14
16       95251           11
17       95051            8
18       59519            8
19       95591            7
20       95510            7
21       59501            5
22     95525.0            4
23        9554            4
24       95159            4
25     95540.0            4
26        9557            3
27       95450            2
28     95570.0            2

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
2826,POP_S_2705252,Student,4309 Bates Rd,McKinleyville,CA,-,2109 Oak Dr,Brooklyn,NY,11211,OutOfState
2191,POP_S_2457633,Student,8508 11th St,Arcata,CA,-,1537 Meadow Rd,Berkeley,CA,94704,BayArea
6407,POP_F_1157200,Faculty,2547 6th St,Eureka,CA,-,2547 6th St,Eureka,CA,95501,Local
7206,POP_S_7239573,Staff/Admin,1402 Bates Rd,McKinleyville,CA,-,1402 Bates Rd,McKinleyville,CA,95519,Local
212,POP_S_5190725,Student,6849 Baldwin St,Arcata,CA,-,5613 Ridge Dr,Ukiah,CA,95482,NorCal
...,...,...,...,...,...,...,...,...,...,...,...
1433,POP_S_7959080,Student,6302 11th St,Arcata,CA,unknown,7180 Pine Ln,Austin,TX,78701,OutOfState
3161,POP_S_7298905,Student,4843 Alliance Rd,Arcata,CA,unknown,8298 Birch St,Boulder,CO,80302,OutOfState
4143,POP_S_4303405,Student,1147 Heartwood Dr,McKinleyville,CA,unknown,6454 Maple Rd,Pasadena,CA,91101,LA
5256,POP_S_6499535,Student,5792 Trinity St,Trinidad,CA,unknown,9878 Sunset St,Redding,CA,96001,NorCal
6201,POP_F_7848576,Faculty,8320 Winchester Ave,McKinleyville,CA,unknown,8320 Winchester Ave,McKinleyville,CA,95519,Local

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_street
----------------------------------------------------------------------
Repeated values and occurrence counts:

          permanent_street  occurrences
0                  unknown           33
1                        -           23
2            5102 Elm Blvd            4
3           5095 Spruce Pl            3
4            6907 Ridge Rd            3
..                     ...          ...
518  1178 Patrick Point Dr            2
519        2911 Myrtle Ave            2
520              3720 H St            2
521    7041 Rohnerville Rd            2
522              9719 H St            2

[523 rows x 2 columns]

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
1476,POP_S_2788201,Student,7267 Parker Creek Rd,Trinidad,CA,95570,-,Berkeley,CA,94704,BayArea
2725,POP_S_8294805,Student,6032 Baldwin St,Arcata,CA,95521,-,Oakland,CA,94612,BayArea
3798,POP_S_4942328,Student,6931 Greenwood Ave,Blue Lake,CA,95525,-,Los Angeles,CA,90026,LA
7078,POP_S_4664145,Staff/Admin,4885 Wabash Ave,Eureka,CA,95501,-,Eureka,CA,95501,Local
3017,POP_S_3117165,Student,7757 11th St,Arcata,CA,95521,-,Daly City,CA,94015,BayArea
...,...,...,...,...,...,...,...,...,...,...,...
6099,POP_F_8223650,Faculty,192 Heartwood Dr,McKinleyville,CA,95519,unknown,McKinleyville,CA,95519,Local
1429,POP_S_1410588,Student,2028 Alliance Rd,Arcata,CA,95521,unknown,Eureka,CA,95501,NorCal
5848,POP_S_4604372,Student,547 Samoa Blvd,Arcata,CA,95521,unknown,Oakland,CA,94612,BayArea
6572,POP_S_4542651,Staff/Admin,6787 J St,Eureka,CA,95501,unknown,Eureka,CA,95501,Local
6498,POP_F_8468697,Faculty,649 J St,Eureka,CA,95501,unknown,Eureka,CA,95501,Local

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_city
----------------------------------------------------------------------
Repeated values and occurrence counts:

    permanent_city  occurrences
0           Eureka          543
1    McKinleyville          321
2           Arcata          288
3         Glendale          271
4          Anaheim          267
5          Fremont          261
6      Los Angeles          258
7         Pasadena          257
8     Santa Monica          249
9        Daly City          243
10      Long Beach          240
11        Berkeley          238
12   San Francisco          236
13         Oakland          220
14        San Jose          207
15         Redding          193
16           Ukiah          187
17      Sacramento          183
18      Santa Rosa          181
19           Chico          170
20         Boulder          166
21  Salt Lake City          166
22        Portland          160
23         Seattle          158
24          Austin          155
25   National City          152
26        Brooklyn          149
27         Phoenix          142
28            Reno          142
29           Boise          139
30         La Mesa          131
31       Oceanside          126
32       Escondido          121
33     Chula Vista          117
34       San Diego          115
35       Blue Lake           66
36         Fortuna           65
37        Trinidad           55
38          EUREKA           33
39    SANTA MONICA           22
40       DALY CITY           22
41          ARCATA           19
42         FREMONT           18
43   MCKINLEYVILLE           18
44        GLENDALE           16
45        BERKELEY           16
46      LONG BEACH           16
47     LOS ANGELES           16
48         OAKLAND           16
49           UKIAH           15
50        PASADENA           15
51          AUSTIN           13
52           CHICO           13
53        PORTLAND           12
54         REDDING           12
55      SACRAMENTO           12
56   SAN FRANCISCO           11
57      SANTA ROSA           11
58         ANAHEIM           10
59        BROOKLYN           10
60            RENO           10
61  SALT LAKE CITY            9
62         BOULDER            8
63         FORTUNA            8
64         PHOENIX            7
65     CHULA VISTA            7
66           BOISE            7
67   NATIONAL CITY            7
68        SAN JOSE            7
69       OCEANSIDE            6
70         SEATTLE            6
71         LA MESA            6
72       ESCONDIDO            5
73       BLUE LAKE            4
74       SAN DIEGO            3

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
1912,POP_S_2058861,Student,7511 Samoa Blvd,Arcata,CA,95521,7531 Maple Ln,ANAHEIM,CA,92801,LA
5723,POP_S_9082017,Student,6192 Heartwood Dr,McKinleyville,CA,95519,4183 Spruce St,ANAHEIM,CA,92801,LA
7698,POP_S_7548306,Student,9846 K St,Eureka,CA,95501,3823 Willow Pl,ANAHEIM,CA,92801,LA
5446,POP_S_7548306,Student,9846 K St,Eureka,CA,95501,3823 Willow Pl,ANAHEIM,CA,92801,LA
214,POP_S_4137422,Student,3641 H St,Arcata,CA,95521,6639 Lake Dr,ANAHEIM,CA,92801,LA
...,...,...,...,...,...,...,...,...,...,...,...
4831,POP_S_2023268,Student,6044 I St,Eureka,CA,95501,1972 Birch Way,Ukiah,CA,95482,NorCal
3509,POP_S_5387139,Student,8461 LK Wood Blvd,Arcata,CA,95521,9047 Spruce Ln,Ukiah,CA,95482,NorCal
5687,POP_S_3216954,Student,5731 14th St,Arcata,California,95521,3805 Elm Ln,Ukiah,CA,95482,NorCal
3452,POP_S_9443876,Student,9960 H St,Eureka,CA,95501,9814 Elm Ave,Ukiah,CA,95482,NorCal
3007,POP_S_1935127,Student,6441 Baldwin St,Arcata,CA,95521,9658 Birch Dr,Ukiah,CA,95482,NorCal

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_state
----------------------------------------------------------------------
Repeated values and occurrence counts:

  permanent_state  occurrences
0              CA         6326
1              UT          175
2              CO          174
3              OR          172
4              TX          168
5              WA          164
6              NY          159
7              NV          152
8              AZ          149
9              ID          146

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
3641,POP_S_2777454,Student,9421 Alliance Rd,Arcata,CA,95521,4765 Vista St,PHOENIX,AZ,85004,OutOfState
4279,POP_S_1215804,Student,3970 LK Wood Blvd,Arcata,CA,95521,4650 Oak Dr,Phoenix,AZ,85004,OutOfState
3105,POP_S_1009044,Student,2123 Janis Ct,Arcata,CA,95521,4841 Ridge Dr,Phoenix,AZ,85004,OutOfState
3098,POP_S_8360262,Studnet,8456 G St,Arcata,CA,95521,3286 Meadow Ln,Phoenix,AZ,85004,OutOfState
4293,POP_S_9367974,Student,4418 14th St,Arcata,CA,95521,7218 Hill Dr,Phoenix,AZ,85004,OutOfState
...,...,...,...,...,...,...,...,...,...,...,...
7635,POP_S_1103247,Student,5618 Bates Rd,McKinleyville,CA,9551,5785 Ridge Way,Seattle,WA,98101,OutOfState
932,POP_S_5300660,Student,1377 Hatchery Rd,Blue Lake,CA,95525,5316 Oak St,Seattle,WA,98101,OutOfState
5001,POP_S_5265496,Student,8183 Dinsmore Dr,Fortuna,CA,95540,5569 Spruce Ave,Seattle,WA,98101,OutOfState
1775,POP_S_1701658,Student,7632 Rohnerville Rd,Fortuna,CA,95540,6173 Canyon Rd,Seattle,WA,98101,OutOfState
4694,POP_S_3501636,Student,6891 11th St,Arcata,CA,95521,3015 Willow Blvd,Seattle,WA,98101,OutOfState

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_zip
----------------------------------------------------------------------
Repeated values and occurrence counts:

    permanent_zip  occurrences
0           95501          576
1           95519          339
2           95521          307
3           91203          287
4           94536          279
5           92801          277
6           90026          274
7           91101          272
8           90401          271
9           94015          265
10          90802          256
11          94704          254
12          94110          247
13          94612          236
14          95112          214
15          96001          205
16          95482          202
17          95814          195
18          95401          192
19          95926          183
20          84111          175
21          80302          174
22          97205          172
23          78701          168
24          98101          164
25          91950          159
26          11211          159
27          89501          152
28          85004          149
29          83702          146
30          91942          137
31          92054          132
32          92025          126
33          91910          124
34          92103          118
35          95540           73
36          95525           70
37          95570           56

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
4716,POP_S_3390717,Student,2927 Winchester Ave,McKinleyville,CA,95519,1505 Spruce Ave,Brooklyn,NY,11211,OutOfState
4713,POP_S_6184160,Student,745 J St,Eureka,CA,95501,3514 Meadow Pl,Brooklyn,NY,11211,OutOfState
61,POP_S_7119154,Student,8431 H St,Arcata,CA,95521,9317 Elm Pl,Brooklyn,NY,11211,OutOfState
60,POP_S_8811547,Student,6339 Bates Rd,McKinleyville,CA,95519,3372 Pine Way,Brooklyn,NY,11211,OutOfState
7783,POP_S_7693823,Student,5449 5th st,Eureka,CA,95501,1642 Sunset Way,Brooklyn,NY,11211,OutOfState
...,...,...,...,...,...,...,...,...,...,...,...
3614,POP_S_3947875,Student,4096 Spears Rd,Arcata,CA,95521,5698 Elm St,Seattle,WA,98101,OutOfState
3505,POP_S_5507293,Student,8492 Spears Rd,Arcata,CA,95521,658 Pine Pl,Seattle,WA,98101,OutOfState
7778,POP_S_9369120,Student,4126 Winchester Ave,McKinleyville,CA,95519,4053 Pine Rd,Seattle,WA,98101,OutOfState
7756,POP_S_7631584,Student,6538 Union St,Arcata,CA,95521.0,1430 Sunset Way,Seattle,WA,98101,OutOfState
7741,POP_S_7586801,Student,7663 Alliance Rd,Arcata,CA,95521,2672 Spruce Ave,Seattle,WA,98101,OutOfState

----------------------------------------------------------------------
PERMANENT ADDRESS: permanent_region
----------------------------------------------------------------------
Repeated values and occurrence counts:

  permanent_region  occurrences
0               LA         1637
1          BayArea         1495
2       OutOfState         1459
3            Local         1257
4           NorCal         1141
5         SanDiego          796

All rows containing those repeated values:

,pop_id,role,current_street,current_city,current_state,current_zip,permanent_street,permanent_city,permanent_state,permanent_zip,permanent_region
7784,POP_S_5614862,Student,4299 5th St,Eureka,ca,95501,4084 Maple Way,Daly City,CA,94015,BayArea
2012,POP_S_3775544,Student,3847 Wabash Ave,Eureka,CA,95501.0,8350 Sunset Blvd,Oakland,CA,94612,BayArea
4646,POP_S_3221715,Student,441 Central Ave,McKinleyville,CA,95519,6942 Ridge Rd,San Francisco,CA,94110,BayArea
3293,POP_S_7438395,Student,9895 Central Ave,McKinleyville,CA,95519,2372 Ridge Pl,Daly City,CA,94015,BayArea
1147,POP_S_9628541,Student,6480 Heartwood Dr,McKinleyville,CA,95519,3094 Birch Blvd,Daly City,CA,94015,BayArea
...,...,...,...,...,...,...,...,...,...,...,...
4080,POP_S_6308236,Student,8827 Murray Rd,McKinelyville,CA,95519,6703 Elm Ave,Oceanside,CA,92054,SanDiego
4077,POP_S_6171444,Student,4291 Hatchery Rd,Blue Lake,CA,95525,7650 Lake Pl,Oceanside,CA,92054,SanDiego
4075,POP_S_5270653,Student,7669 Harris St,Eureka,Ca,95501,5994 Spruce Blvd,San Diego,CA,92103,SanDiego
1449,POP_S_2411638,Student,4549 14th St,Arcata,CA,95521,8634 Willow Way,National City,CA,91950,SanDiego
1483,POP_S_2205687,Student,1669 Spears Rd,Arcata,CA,95521,6000 Vista St,Escondido,CA,92025,SanDiego

In [14]:
# Find Case and Whitespace
def audit_format_variations(df, columns, address_type):
    for column in columns:
        # Convert to strings, trim outer spaces, ignore case
        normalized = (
            df[column]
            .astype("string")
            .str.strip()
            .str.casefold()
        )

        # Preserve original spellings for comparison
        temp = pd.DataFrame({
            "normalized_value": normalized,
            "original_value": df[column]
        }).dropna(subset=["normalized_value"])

        variations = (
            temp.groupby("normalized_value")["original_value"]
            .agg(lambda x: sorted(x.unique().tolist()))
        )

        # Keep only groups with multiple original representations
        variations = variations[variations.map(len) > 1]

        if not variations.empty:
            print(
                f"\n{address_type} FORMAT VARIATIONS: {column}"
            )
            display(variations.rename("original_variations").reset_index())


print("\n" + "=" * 80)
print("5. CASE AND WHITESPACE VARIATIONS")
print("=" * 80)

audit_format_variations(
    pop,
    ["role"] + current_columns + permanent_columns,
    "ROLE / ADDRESS"
)

print("\n" + "=" * 80)
print("DATA-QUALITY AUDIT COMPLETE")
print("=" * 80)

================================================================================
5. CASE AND WHITESPACE VARIATIONS
================================================================================

ROLE / ADDRESS FORMAT VARIATIONS: role

  normalized_value                      original_variations
0          faculty    [FACULTY, Faculty, Faculty , faculty]
1      staff/admin  [STAFF/ADMIN, Staff/Admin, staff/admin]
2          student              [STUDENT, Student, student]

ROLE / ADDRESS FORMAT VARIATIONS: current_street

   normalized_value                   original_variations
0     3200 janis ct        [3200 Janis Ct, 3200 janis ct]
1          322 h st                  [322 H St, 322 h st]
2    3334 murray rd      [3334 MURRAY RD, 3334 Murray Rd]
3  4742 alliance rd  [4742 ALLIANCE RD, 4742 Alliance Rd]
4  5073 central ave  [5073 Central Ave, 5073 central ave]
5      6141 11th st          [6141 11th St, 6141 11th st]
6   6325 myrtle ave    [6325 Myrtle Ave, 6325 myrtle ave]
7          636 g st                  [636 G St, 636 g st]
8   6453 wabash ave    [6453 Wabash Ave, 6453 wabash ave]
9          659 h st                  [659 H St, 659 h st]

ROLE / ADDRESS FORMAT VARIATIONS: current_city

  normalized_value                            original_variations
0           arcata                       [ARCATA, Arcata, arcata]
1          arcatra                             [ARCATRA, Arcatra]
2        blue lake                         [BLUE LAKE, Blue Lake]
3           eureka                       [EUREKA, Eureka, eureka]
4          fortuna                             [Fortuna, fortuna]
5    mckinleyville  [MCKINLEYVILLE, McKinleyville, mckinleyville]
6         trinidad                           [TRINIDAD, Trinidad]

ROLE / ADDRESS FORMAT VARIATIONS: current_state

  normalized_value original_variations
0               ca        [CA, Ca, ca]

ROLE / ADDRESS FORMAT VARIATIONS: permanent_city

   normalized_value               original_variations
0           anaheim                [ANAHEIM, Anaheim]
1            arcata                  [ARCATA, Arcata]
2            austin                  [AUSTIN, Austin]
3          berkeley              [BERKELEY, Berkeley]
4         blue lake            [BLUE LAKE, Blue Lake]
5             boise                    [BOISE, Boise]
6           boulder                [BOULDER, Boulder]
7          brooklyn              [BROOKLYN, Brooklyn]
8             chico                    [CHICO, Chico]
9       chula vista        [CHULA VISTA, Chula Vista]
10        daly city            [DALY CITY, Daly City]
11        escondido            [ESCONDIDO, Escondido]
12           eureka                  [EUREKA, Eureka]
13          fortuna                [FORTUNA, Fortuna]
14          fremont                [FREMONT, Fremont]
15         glendale              [GLENDALE, Glendale]
16          la mesa                [LA MESA, La Mesa]
17       long beach          [LONG BEACH, Long Beach]
18      los angeles        [LOS ANGELES, Los Angeles]
19    mckinleyville    [MCKINLEYVILLE, McKinleyville]
20    national city    [NATIONAL CITY, National City]
21          oakland                [OAKLAND, Oakland]
22        oceanside            [OCEANSIDE, Oceanside]
23         pasadena              [PASADENA, Pasadena]
24          phoenix                [PHOENIX, Phoenix]
25         portland              [PORTLAND, Portland]
26          redding                [REDDING, Redding]
27             reno                      [RENO, Reno]
28       sacramento          [SACRAMENTO, Sacramento]
29   salt lake city  [SALT LAKE CITY, Salt Lake City]
30        san diego            [SAN DIEGO, San Diego]
31    san francisco    [SAN FRANCISCO, San Francisco]
32         san jose              [SAN JOSE, San Jose]
33     santa monica      [SANTA MONICA, Santa Monica]
34       santa rosa          [SANTA ROSA, Santa Rosa]
35          seattle                [SEATTLE, Seattle]
36         trinidad              [TRINIDAD, Trinidad]
37            ukiah                    [UKIAH, Ukiah]

================================================================================
DATA-QUALITY AUDIT COMPLETE
================================================================================